/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultExamIdRouteImport } from './routes/result.$examId'
import { Route as QuizExamIdRouteImport } from './routes/quiz.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultExamIdRoute = ResultExamIdRouteImport.update({
  id: '/result/$examId',
  path: '/result/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizExamIdRoute = QuizExamIdRouteImport.update({
  id: '/quiz/$examId',
  path: '/quiz/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz/$examId': typeof QuizExamIdRoute
  '/result/$examId': typeof ResultExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz/$examId': typeof QuizExamIdRoute
  '/result/$examId': typeof ResultExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz/$examId': typeof QuizExamIdRoute
  '/result/$examId': typeof ResultExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz/$examId' | '/result/$examId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz/$examId' | '/result/$examId'
  id: '__root__' | '/' | '/quiz/$examId' | '/result/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizExamIdRoute: typeof QuizExamIdRoute
  ResultExamIdRoute: typeof ResultExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$examId': {
      id: '/result/$examId'
      path: '/result/$examId'
      fullPath: '/result/$examId'
      preLoaderRoute: typeof ResultExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$examId': {
      id: '/quiz/$examId'
      path: '/quiz/$examId'
      fullPath: '/quiz/$examId'
      preLoaderRoute: typeof QuizExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizExamIdRoute: QuizExamIdRoute,
  ResultExamIdRoute: ResultExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
